// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: objectives/v1alpha1/objectives.proto

package objectivesv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LabelMatcher_Type int32

const (
	LabelMatcher_EQ  LabelMatcher_Type = 0
	LabelMatcher_NEQ LabelMatcher_Type = 1
	LabelMatcher_RE  LabelMatcher_Type = 2
	LabelMatcher_NRE LabelMatcher_Type = 3
)

// Enum value maps for LabelMatcher_Type.
var (
	LabelMatcher_Type_name = map[int32]string{
		0: "EQ",
		1: "NEQ",
		2: "RE",
		3: "NRE",
	}
	LabelMatcher_Type_value = map[string]int32{
		"EQ":  0,
		"NEQ": 1,
		"RE":  2,
		"NRE": 3,
	}
)

func (x LabelMatcher_Type) Enum() *LabelMatcher_Type {
	p := new(LabelMatcher_Type)
	*p = x
	return p
}

func (x LabelMatcher_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabelMatcher_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_objectives_v1alpha1_objectives_proto_enumTypes[0].Descriptor()
}

func (LabelMatcher_Type) Type() protoreflect.EnumType {
	return &file_objectives_v1alpha1_objectives_proto_enumTypes[0]
}

func (x LabelMatcher_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabelMatcher_Type.Descriptor instead.
func (LabelMatcher_Type) EnumDescriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{11, 0}
}

type Alert_State int32

const (
	Alert_inactive Alert_State = 0
	Alert_pending  Alert_State = 1
	Alert_firing   Alert_State = 2
)

// Enum value maps for Alert_State.
var (
	Alert_State_name = map[int32]string{
		0: "inactive",
		1: "pending",
		2: "firing",
	}
	Alert_State_value = map[string]int32{
		"inactive": 0,
		"pending":  1,
		"firing":   2,
	}
)

func (x Alert_State) Enum() *Alert_State {
	p := new(Alert_State)
	*p = x
	return p
}

func (x Alert_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alert_State) Descriptor() protoreflect.EnumDescriptor {
	return file_objectives_v1alpha1_objectives_proto_enumTypes[1].Descriptor()
}

func (Alert_State) Type() protoreflect.EnumType {
	return &file_objectives_v1alpha1_objectives_proto_enumTypes[1]
}

func (x Alert_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alert_State.Descriptor instead.
func (Alert_State) EnumDescriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{19, 0}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Grouping      string                 `protobuf:"bytes,2,opt,name=grouping,proto3" json:"grouping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *ListRequest) GetGrouping() string {
	if x != nil {
		return x.Grouping
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objectives    []*Objective           `protobuf:"bytes,1,rep,name=objectives,proto3" json:"objectives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetObjectives() []*Objective {
	if x != nil {
		return x.Objectives
	}
	return nil
}

type Objective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Target        float64                `protobuf:"fixed64,2,opt,name=target,proto3" json:"target,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Indicator     *Indicator             `protobuf:"bytes,5,opt,name=indicator,proto3" json:"indicator,omitempty"`
	Config        string                 `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	Queries       *Queries               `protobuf:"bytes,7,opt,name=queries,proto3" json:"queries,omitempty"`
	Alerting      *Alerting              `protobuf:"bytes,8,opt,name=alerting,proto3" json:"alerting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Objective) Reset() {
	*x = Objective{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Objective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objective) ProtoMessage() {}

func (x *Objective) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objective.ProtoReflect.Descriptor instead.
func (*Objective) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{2}
}

func (x *Objective) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Objective) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Objective) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *Objective) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Objective) GetIndicator() *Indicator {
	if x != nil {
		return x.Indicator
	}
	return nil
}

func (x *Objective) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Objective) GetQueries() *Queries {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *Objective) GetAlerting() *Alerting {
	if x != nil {
		return x.Alerting
	}
	return nil
}

type Indicator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Options:
	//
	//	*Indicator_Ratio
	//	*Indicator_Latency
	//	*Indicator_BoolGauge
	//	*Indicator_LatencyNative
	Options       isIndicator_Options `protobuf_oneof:"options"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Indicator) Reset() {
	*x = Indicator{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Indicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indicator) ProtoMessage() {}

func (x *Indicator) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indicator.ProtoReflect.Descriptor instead.
func (*Indicator) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{3}
}

func (x *Indicator) GetOptions() isIndicator_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Indicator) GetRatio() *Ratio {
	if x != nil {
		if x, ok := x.Options.(*Indicator_Ratio); ok {
			return x.Ratio
		}
	}
	return nil
}

func (x *Indicator) GetLatency() *Latency {
	if x != nil {
		if x, ok := x.Options.(*Indicator_Latency); ok {
			return x.Latency
		}
	}
	return nil
}

func (x *Indicator) GetBoolGauge() *BoolGauge {
	if x != nil {
		if x, ok := x.Options.(*Indicator_BoolGauge); ok {
			return x.BoolGauge
		}
	}
	return nil
}

func (x *Indicator) GetLatencyNative() *LatencyNative {
	if x != nil {
		if x, ok := x.Options.(*Indicator_LatencyNative); ok {
			return x.LatencyNative
		}
	}
	return nil
}

type isIndicator_Options interface {
	isIndicator_Options()
}

type Indicator_Ratio struct {
	Ratio *Ratio `protobuf:"bytes,1,opt,name=ratio,proto3,oneof"`
}

type Indicator_Latency struct {
	Latency *Latency `protobuf:"bytes,2,opt,name=latency,proto3,oneof"`
}

type Indicator_BoolGauge struct {
	BoolGauge *BoolGauge `protobuf:"bytes,3,opt,name=boolGauge,proto3,oneof"`
}

type Indicator_LatencyNative struct {
	LatencyNative *LatencyNative `protobuf:"bytes,4,opt,name=latency_native,json=latencyNative,proto3,oneof"`
}

func (*Indicator_Ratio) isIndicator_Options() {}

func (*Indicator_Latency) isIndicator_Options() {}

func (*Indicator_BoolGauge) isIndicator_Options() {}

func (*Indicator_LatencyNative) isIndicator_Options() {}

type Ratio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *Query                 `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	Errors        *Query                 `protobuf:"bytes,2,opt,name=errors,proto3" json:"errors,omitempty"`
	Grouping      []string               `protobuf:"bytes,3,rep,name=grouping,proto3" json:"grouping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ratio) Reset() {
	*x = Ratio{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ratio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ratio) ProtoMessage() {}

func (x *Ratio) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ratio.ProtoReflect.Descriptor instead.
func (*Ratio) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{4}
}

func (x *Ratio) GetTotal() *Query {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *Ratio) GetErrors() *Query {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *Ratio) GetGrouping() []string {
	if x != nil {
		return x.Grouping
	}
	return nil
}

type Latency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *Query                 `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       *Query                 `protobuf:"bytes,2,opt,name=success,proto3" json:"success,omitempty"`
	Grouping      []string               `protobuf:"bytes,3,rep,name=grouping,proto3" json:"grouping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Latency) Reset() {
	*x = Latency{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Latency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Latency) ProtoMessage() {}

func (x *Latency) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Latency.ProtoReflect.Descriptor instead.
func (*Latency) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{5}
}

func (x *Latency) GetTotal() *Query {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *Latency) GetSuccess() *Query {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *Latency) GetGrouping() []string {
	if x != nil {
		return x.Grouping
	}
	return nil
}

type LatencyNative struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *Query                 `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	Latency       string                 `protobuf:"bytes,2,opt,name=latency,proto3" json:"latency,omitempty"`
	Grouping      []string               `protobuf:"bytes,3,rep,name=grouping,proto3" json:"grouping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyNative) Reset() {
	*x = LatencyNative{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyNative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyNative) ProtoMessage() {}

func (x *LatencyNative) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyNative.ProtoReflect.Descriptor instead.
func (*LatencyNative) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{6}
}

func (x *LatencyNative) GetTotal() *Query {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *LatencyNative) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

func (x *LatencyNative) GetGrouping() []string {
	if x != nil {
		return x.Grouping
	}
	return nil
}

type BoolGauge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoolGauge     *Query                 `protobuf:"bytes,1,opt,name=boolGauge,proto3" json:"boolGauge,omitempty"`
	Grouping      []string               `protobuf:"bytes,3,rep,name=grouping,proto3" json:"grouping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolGauge) Reset() {
	*x = BoolGauge{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolGauge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolGauge) ProtoMessage() {}

func (x *BoolGauge) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolGauge.ProtoReflect.Descriptor instead.
func (*BoolGauge) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{7}
}

func (x *BoolGauge) GetBoolGauge() *Query {
	if x != nil {
		return x.BoolGauge
	}
	return nil
}

func (x *BoolGauge) GetGrouping() []string {
	if x != nil {
		return x.Grouping
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Matchers      []*LabelMatcher        `protobuf:"bytes,3,rep,name=matchers,proto3" json:"matchers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{8}
}

func (x *Query) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *Query) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Query) GetMatchers() []*LabelMatcher {
	if x != nil {
		return x.Matchers
	}
	return nil
}

type Queries struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CountTotal       string                 `protobuf:"bytes,1,opt,name=countTotal,proto3" json:"countTotal,omitempty"`
	CountErrors      string                 `protobuf:"bytes,2,opt,name=countErrors,proto3" json:"countErrors,omitempty"`
	GraphErrorBudget string                 `protobuf:"bytes,3,opt,name=graphErrorBudget,proto3" json:"graphErrorBudget,omitempty"`
	GraphRequests    string                 `protobuf:"bytes,4,opt,name=graphRequests,proto3" json:"graphRequests,omitempty"`
	GraphErrors      string                 `protobuf:"bytes,5,opt,name=graphErrors,proto3" json:"graphErrors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Queries) Reset() {
	*x = Queries{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queries) ProtoMessage() {}

func (x *Queries) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queries.ProtoReflect.Descriptor instead.
func (*Queries) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{9}
}

func (x *Queries) GetCountTotal() string {
	if x != nil {
		return x.CountTotal
	}
	return ""
}

func (x *Queries) GetCountErrors() string {
	if x != nil {
		return x.CountErrors
	}
	return ""
}

func (x *Queries) GetGraphErrorBudget() string {
	if x != nil {
		return x.GraphErrorBudget
	}
	return ""
}

func (x *Queries) GetGraphRequests() string {
	if x != nil {
		return x.GraphRequests
	}
	return ""
}

func (x *Queries) GetGraphErrors() string {
	if x != nil {
		return x.GraphErrors
	}
	return ""
}

type Alerting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Burnrates     bool                   `protobuf:"varint,1,opt,name=burnrates,proto3" json:"burnrates,omitempty"`
	Absent        bool                   `protobuf:"varint,2,opt,name=absent,proto3" json:"absent,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AbsentName    string                 `protobuf:"bytes,4,opt,name=absent_name,json=absentName,proto3" json:"absent_name,omitempty"`
	BurnRateType  string                 `protobuf:"bytes,5,opt,name=burn_rate_type,json=burnRateType,proto3" json:"burn_rate_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alerting) Reset() {
	*x = Alerting{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alerting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alerting) ProtoMessage() {}

func (x *Alerting) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alerting.ProtoReflect.Descriptor instead.
func (*Alerting) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{10}
}

func (x *Alerting) GetBurnrates() bool {
	if x != nil {
		return x.Burnrates
	}
	return false
}

func (x *Alerting) GetAbsent() bool {
	if x != nil {
		return x.Absent
	}
	return false
}

func (x *Alerting) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alerting) GetAbsentName() string {
	if x != nil {
		return x.AbsentName
	}
	return ""
}

func (x *Alerting) GetBurnRateType() string {
	if x != nil {
		return x.BurnRateType
	}
	return ""
}

// Copied from Prometheus.
// Matcher specifies a rule, which can match or set of labels or not.
type LabelMatcher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LabelMatcher_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=objectives.v1alpha1.LabelMatcher_Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelMatcher) Reset() {
	*x = LabelMatcher{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelMatcher) ProtoMessage() {}

func (x *LabelMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelMatcher.ProtoReflect.Descriptor instead.
func (*LabelMatcher) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{11}
}

func (x *LabelMatcher) GetType() LabelMatcher_Type {
	if x != nil {
		return x.Type
	}
	return LabelMatcher_EQ
}

func (x *LabelMatcher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabelMatcher) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Grouping      string                 `protobuf:"bytes,2,opt,name=grouping,proto3" json:"grouping,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatusRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *GetStatusRequest) GetGrouping() string {
	if x != nil {
		return x.Grouping
	}
	return ""
}

func (x *GetStatusRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        []*ObjectiveStatus     `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatusResponse) GetStatus() []*ObjectiveStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ObjectiveStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Availability  *Availability          `protobuf:"bytes,2,opt,name=availability,proto3" json:"availability,omitempty"`
	Budget        *Budget                `protobuf:"bytes,3,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectiveStatus) Reset() {
	*x = ObjectiveStatus{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectiveStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectiveStatus) ProtoMessage() {}

func (x *ObjectiveStatus) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectiveStatus.ProtoReflect.Descriptor instead.
func (*ObjectiveStatus) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{14}
}

func (x *ObjectiveStatus) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectiveStatus) GetAvailability() *Availability {
	if x != nil {
		return x.Availability
	}
	return nil
}

func (x *ObjectiveStatus) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type Availability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentage    float64                `protobuf:"fixed64,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	Errors        float64                `protobuf:"fixed64,3,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Availability) Reset() {
	*x = Availability{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Availability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Availability) ProtoMessage() {}

func (x *Availability) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Availability.ProtoReflect.Descriptor instead.
func (*Availability) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{15}
}

func (x *Availability) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Availability) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Availability) GetErrors() float64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	Remaining     float64                `protobuf:"fixed64,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Max           float64                `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{16}
}

func (x *Budget) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Budget) GetRemaining() float64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *Budget) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type GetAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Grouping      string                 `protobuf:"bytes,2,opt,name=grouping,proto3" json:"grouping,omitempty"`
	Inactive      bool                   `protobuf:"varint,3,opt,name=inactive,proto3" json:"inactive,omitempty"`
	Current       bool                   `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsRequest) Reset() {
	*x = GetAlertsRequest{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsRequest) ProtoMessage() {}

func (x *GetAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsRequest.ProtoReflect.Descriptor instead.
func (*GetAlertsRequest) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{17}
}

func (x *GetAlertsRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *GetAlertsRequest) GetGrouping() string {
	if x != nil {
		return x.Grouping
	}
	return ""
}

func (x *GetAlertsRequest) GetInactive() bool {
	if x != nil {
		return x.Inactive
	}
	return false
}

func (x *GetAlertsRequest) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

type GetAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsResponse) Reset() {
	*x = GetAlertsResponse{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsResponse) ProtoMessage() {}

func (x *GetAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetAlertsResponse) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{18}
}

func (x *GetAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	For           *durationpb.Duration   `protobuf:"bytes,3,opt,name=for,proto3" json:"for,omitempty"`
	Factor        float64                `protobuf:"fixed64,4,opt,name=factor,proto3" json:"factor,omitempty"`
	State         Alert_State            `protobuf:"varint,5,opt,name=state,proto3,enum=objectives.v1alpha1.Alert_State" json:"state,omitempty"`
	Short         *Burnrate              `protobuf:"bytes,6,opt,name=short,proto3" json:"short,omitempty"`
	Long          *Burnrate              `protobuf:"bytes,7,opt,name=long,proto3" json:"long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{19}
}

func (x *Alert) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetFor() *durationpb.Duration {
	if x != nil {
		return x.For
	}
	return nil
}

func (x *Alert) GetFactor() float64 {
	if x != nil {
		return x.Factor
	}
	return 0
}

func (x *Alert) GetState() Alert_State {
	if x != nil {
		return x.State
	}
	return Alert_inactive
}

func (x *Alert) GetShort() *Burnrate {
	if x != nil {
		return x.Short
	}
	return nil
}

func (x *Alert) GetLong() *Burnrate {
	if x != nil {
		return x.Long
	}
	return nil
}

type Burnrate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Window        *durationpb.Duration   `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`
	Current       float64                `protobuf:"fixed64,2,opt,name=current,proto3" json:"current,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Burnrate) Reset() {
	*x = Burnrate{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Burnrate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Burnrate) ProtoMessage() {}

func (x *Burnrate) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Burnrate.ProtoReflect.Descriptor instead.
func (*Burnrate) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{20}
}

func (x *Burnrate) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *Burnrate) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Burnrate) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GraphErrorBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Grouping      string                 `protobuf:"bytes,2,opt,name=grouping,proto3" json:"grouping,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphErrorBudgetRequest) Reset() {
	*x = GraphErrorBudgetRequest{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphErrorBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphErrorBudgetRequest) ProtoMessage() {}

func (x *GraphErrorBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphErrorBudgetRequest.ProtoReflect.Descriptor instead.
func (*GraphErrorBudgetRequest) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{21}
}

func (x *GraphErrorBudgetRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *GraphErrorBudgetRequest) GetGrouping() string {
	if x != nil {
		return x.Grouping
	}
	return ""
}

func (x *GraphErrorBudgetRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GraphErrorBudgetRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type GraphErrorBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeseries    *Timeseries            `protobuf:"bytes,1,opt,name=timeseries,proto3" json:"timeseries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphErrorBudgetResponse) Reset() {
	*x = GraphErrorBudgetResponse{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphErrorBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphErrorBudgetResponse) ProtoMessage() {}

func (x *GraphErrorBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphErrorBudgetResponse.ProtoReflect.Descriptor instead.
func (*GraphErrorBudgetResponse) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{22}
}

func (x *GraphErrorBudgetResponse) GetTimeseries() *Timeseries {
	if x != nil {
		return x.Timeseries
	}
	return nil
}

type GraphRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Grouping      string                 `protobuf:"bytes,2,opt,name=grouping,proto3" json:"grouping,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphRateRequest) Reset() {
	*x = GraphRateRequest{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRateRequest) ProtoMessage() {}

func (x *GraphRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRateRequest.ProtoReflect.Descriptor instead.
func (*GraphRateRequest) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{23}
}

func (x *GraphRateRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *GraphRateRequest) GetGrouping() string {
	if x != nil {
		return x.Grouping
	}
	return ""
}

func (x *GraphRateRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GraphRateRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type GraphRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeseries    *Timeseries            `protobuf:"bytes,1,opt,name=timeseries,proto3" json:"timeseries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphRateResponse) Reset() {
	*x = GraphRateResponse{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRateResponse) ProtoMessage() {}

func (x *GraphRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRateResponse.ProtoReflect.Descriptor instead.
func (*GraphRateResponse) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{24}
}

func (x *GraphRateResponse) GetTimeseries() *Timeseries {
	if x != nil {
		return x.Timeseries
	}
	return nil
}

type GraphErrorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Grouping      string                 `protobuf:"bytes,2,opt,name=grouping,proto3" json:"grouping,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphErrorsRequest) Reset() {
	*x = GraphErrorsRequest{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphErrorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphErrorsRequest) ProtoMessage() {}

func (x *GraphErrorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphErrorsRequest.ProtoReflect.Descriptor instead.
func (*GraphErrorsRequest) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{25}
}

func (x *GraphErrorsRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *GraphErrorsRequest) GetGrouping() string {
	if x != nil {
		return x.Grouping
	}
	return ""
}

func (x *GraphErrorsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GraphErrorsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type GraphErrorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeseries    *Timeseries            `protobuf:"bytes,1,opt,name=timeseries,proto3" json:"timeseries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphErrorsResponse) Reset() {
	*x = GraphErrorsResponse{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphErrorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphErrorsResponse) ProtoMessage() {}

func (x *GraphErrorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphErrorsResponse.ProtoReflect.Descriptor instead.
func (*GraphErrorsResponse) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{26}
}

func (x *GraphErrorsResponse) GetTimeseries() *Timeseries {
	if x != nil {
		return x.Timeseries
	}
	return nil
}

type Timeseries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []string               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Series        []*Series              `protobuf:"bytes,3,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timeseries) Reset() {
	*x = Timeseries{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timeseries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeseries) ProtoMessage() {}

func (x *Timeseries) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeseries.ProtoReflect.Descriptor instead.
func (*Timeseries) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{27}
}

func (x *Timeseries) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Timeseries) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Timeseries) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{28}
}

func (x *Series) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type GraphDurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Grouping      string                 `protobuf:"bytes,2,opt,name=grouping,proto3" json:"grouping,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphDurationRequest) Reset() {
	*x = GraphDurationRequest{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphDurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphDurationRequest) ProtoMessage() {}

func (x *GraphDurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphDurationRequest.ProtoReflect.Descriptor instead.
func (*GraphDurationRequest) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{29}
}

func (x *GraphDurationRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *GraphDurationRequest) GetGrouping() string {
	if x != nil {
		return x.Grouping
	}
	return ""
}

func (x *GraphDurationRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GraphDurationRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type GraphDurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeseries    []*Timeseries          `protobuf:"bytes,1,rep,name=timeseries,proto3" json:"timeseries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphDurationResponse) Reset() {
	*x = GraphDurationResponse{}
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphDurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphDurationResponse) ProtoMessage() {}

func (x *GraphDurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectives_v1alpha1_objectives_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphDurationResponse.ProtoReflect.Descriptor instead.
func (*GraphDurationResponse) Descriptor() ([]byte, []int) {
	return file_objectives_v1alpha1_objectives_proto_rawDescGZIP(), []int{30}
}

func (x *GraphDurationResponse) GetTimeseries() []*Timeseries {
	if x != nil {
		return x.Timeseries
	}
	return nil
}

var File_objectives_v1alpha1_objectives_proto protoreflect.FileDescriptor

const file_objectives_v1alpha1_objectives_proto_rawDesc = "" +
	"\n" +
	"$objectives/v1alpha1/objectives.proto\x12\x13objectives.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\vListRequest\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x1a\n" +
	"\bgrouping\x18\x02 \x01(\tR\bgrouping\"N\n" +
	"\fListResponse\x12>\n" +
	"\n" +
	"objectives\x18\x01 \x03(\v2\x1e.objectives.v1alpha1.ObjectiveR\n" +
	"objectives\"\xc0\x03\n" +
	"\tObjective\x12B\n" +
	"\x06labels\x18\x01 \x03(\v2*.objectives.v1alpha1.Objective.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x01R\x06target\x121\n" +
	"\x06window\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x06window\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12<\n" +
	"\tindicator\x18\x05 \x01(\v2\x1e.objectives.v1alpha1.IndicatorR\tindicator\x12\x16\n" +
	"\x06config\x18\x06 \x01(\tR\x06config\x126\n" +
	"\aqueries\x18\a \x01(\v2\x1c.objectives.v1alpha1.QueriesR\aqueries\x129\n" +
	"\balerting\x18\b \x01(\v2\x1d.objectives.v1alpha1.AlertingR\balerting\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x02\n" +
	"\tIndicator\x122\n" +
	"\x05ratio\x18\x01 \x01(\v2\x1a.objectives.v1alpha1.RatioH\x00R\x05ratio\x128\n" +
	"\alatency\x18\x02 \x01(\v2\x1c.objectives.v1alpha1.LatencyH\x00R\alatency\x12>\n" +
	"\tboolGauge\x18\x03 \x01(\v2\x1e.objectives.v1alpha1.BoolGaugeH\x00R\tboolGauge\x12K\n" +
	"\x0elatency_native\x18\x04 \x01(\v2\".objectives.v1alpha1.LatencyNativeH\x00R\rlatencyNativeB\t\n" +
	"\aoptions\"\x89\x01\n" +
	"\x05Ratio\x120\n" +
	"\x05total\x18\x01 \x01(\v2\x1a.objectives.v1alpha1.QueryR\x05total\x122\n" +
	"\x06errors\x18\x02 \x01(\v2\x1a.objectives.v1alpha1.QueryR\x06errors\x12\x1a\n" +
	"\bgrouping\x18\x03 \x03(\tR\bgrouping\"\x8d\x01\n" +
	"\aLatency\x120\n" +
	"\x05total\x18\x01 \x01(\v2\x1a.objectives.v1alpha1.QueryR\x05total\x124\n" +
	"\asuccess\x18\x02 \x01(\v2\x1a.objectives.v1alpha1.QueryR\asuccess\x12\x1a\n" +
	"\bgrouping\x18\x03 \x03(\tR\bgrouping\"w\n" +
	"\rLatencyNative\x120\n" +
	"\x05total\x18\x01 \x01(\v2\x1a.objectives.v1alpha1.QueryR\x05total\x12\x18\n" +
	"\alatency\x18\x02 \x01(\tR\alatency\x12\x1a\n" +
	"\bgrouping\x18\x03 \x03(\tR\bgrouping\"a\n" +
	"\tBoolGauge\x128\n" +
	"\tboolGauge\x18\x01 \x01(\v2\x1a.objectives.v1alpha1.QueryR\tboolGauge\x12\x1a\n" +
	"\bgrouping\x18\x03 \x03(\tR\bgrouping\"r\n" +
	"\x05Query\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12=\n" +
	"\bmatchers\x18\x03 \x03(\v2!.objectives.v1alpha1.LabelMatcherR\bmatchers\"\xbf\x01\n" +
	"\aQueries\x12\x1e\n" +
	"\n" +
	"countTotal\x18\x01 \x01(\tR\n" +
	"countTotal\x12 \n" +
	"\vcountErrors\x18\x02 \x01(\tR\vcountErrors\x12*\n" +
	"\x10graphErrorBudget\x18\x03 \x01(\tR\x10graphErrorBudget\x12$\n" +
	"\rgraphRequests\x18\x04 \x01(\tR\rgraphRequests\x12 \n" +
	"\vgraphErrors\x18\x05 \x01(\tR\vgraphErrors\"\x9b\x01\n" +
	"\bAlerting\x12\x1c\n" +
	"\tburnrates\x18\x01 \x01(\bR\tburnrates\x12\x16\n" +
	"\x06absent\x18\x02 \x01(\bR\x06absent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vabsent_name\x18\x04 \x01(\tR\n" +
	"absentName\x12$\n" +
	"\x0eburn_rate_type\x18\x05 \x01(\tR\fburnRateType\"\x9e\x01\n" +
	"\fLabelMatcher\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.objectives.v1alpha1.LabelMatcher.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"(\n" +
	"\x04Type\x12\x06\n" +
	"\x02EQ\x10\x00\x12\a\n" +
	"\x03NEQ\x10\x01\x12\x06\n" +
	"\x02RE\x10\x02\x12\a\n" +
	"\x03NRE\x10\x03\"r\n" +
	"\x10GetStatusRequest\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x1a\n" +
	"\bgrouping\x18\x02 \x01(\tR\bgrouping\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"Q\n" +
	"\x11GetStatusResponse\x12<\n" +
	"\x06status\x18\x01 \x03(\v2$.objectives.v1alpha1.ObjectiveStatusR\x06status\"\x92\x02\n" +
	"\x0fObjectiveStatus\x12H\n" +
	"\x06labels\x18\x01 \x03(\v20.objectives.v1alpha1.ObjectiveStatus.LabelsEntryR\x06labels\x12E\n" +
	"\favailability\x18\x02 \x01(\v2!.objectives.v1alpha1.AvailabilityR\favailability\x123\n" +
	"\x06budget\x18\x03 \x01(\v2\x1b.objectives.v1alpha1.BudgetR\x06budget\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\fAvailability\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x01R\n" +
	"percentage\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x01R\x06errors\"N\n" +
	"\x06Budget\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x01R\tremaining\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x01R\x03max\"x\n" +
	"\x10GetAlertsRequest\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x1a\n" +
	"\bgrouping\x18\x02 \x01(\tR\bgrouping\x12\x1a\n" +
	"\binactive\x18\x03 \x01(\bR\binactive\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\bR\acurrent\"G\n" +
	"\x11GetAlertsResponse\x122\n" +
	"\x06alerts\x18\x01 \x03(\v2\x1a.objectives.v1alpha1.AlertR\x06alerts\"\xb3\x03\n" +
	"\x05Alert\x12>\n" +
	"\x06labels\x18\x01 \x03(\v2&.objectives.v1alpha1.Alert.LabelsEntryR\x06labels\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12+\n" +
	"\x03for\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03for\x12\x16\n" +
	"\x06factor\x18\x04 \x01(\x01R\x06factor\x126\n" +
	"\x05state\x18\x05 \x01(\x0e2 .objectives.v1alpha1.Alert.StateR\x05state\x123\n" +
	"\x05short\x18\x06 \x01(\v2\x1d.objectives.v1alpha1.BurnrateR\x05short\x121\n" +
	"\x04long\x18\a \x01(\v2\x1d.objectives.v1alpha1.BurnrateR\x04long\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x05State\x12\f\n" +
	"\binactive\x10\x00\x12\v\n" +
	"\apending\x10\x01\x12\n" +
	"\n" +
	"\x06firing\x10\x02\"m\n" +
	"\bBurnrate\x121\n" +
	"\x06window\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x06window\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x01R\acurrent\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\"\xa9\x01\n" +
	"\x17GraphErrorBudgetRequest\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x1a\n" +
	"\bgrouping\x18\x02 \x01(\tR\bgrouping\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"[\n" +
	"\x18GraphErrorBudgetResponse\x12?\n" +
	"\n" +
	"timeseries\x18\x01 \x01(\v2\x1f.objectives.v1alpha1.TimeseriesR\n" +
	"timeseries\"\xa2\x01\n" +
	"\x10GraphRateRequest\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x1a\n" +
	"\bgrouping\x18\x02 \x01(\tR\bgrouping\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"T\n" +
	"\x11GraphRateResponse\x12?\n" +
	"\n" +
	"timeseries\x18\x01 \x01(\v2\x1f.objectives.v1alpha1.TimeseriesR\n" +
	"timeseries\"\xa4\x01\n" +
	"\x12GraphErrorsRequest\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x1a\n" +
	"\bgrouping\x18\x02 \x01(\tR\bgrouping\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"V\n" +
	"\x13GraphErrorsResponse\x12?\n" +
	"\n" +
	"timeseries\x18\x01 \x01(\v2\x1f.objectives.v1alpha1.TimeseriesR\n" +
	"timeseries\"o\n" +
	"\n" +
	"Timeseries\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x123\n" +
	"\x06series\x18\x03 \x03(\v2\x1b.objectives.v1alpha1.SeriesR\x06series\" \n" +
	"\x06Series\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"\xa6\x01\n" +
	"\x14GraphDurationRequest\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x1a\n" +
	"\bgrouping\x18\x02 \x01(\tR\bgrouping\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"X\n" +
	"\x15GraphDurationResponse\x12?\n" +
	"\n" +
	"timeseries\x18\x01 \x03(\v2\x1f.objectives.v1alpha1.TimeseriesR\n" +
	"timeseries2\xbc\x05\n" +
	"\x10ObjectiveService\x12M\n" +
	"\x04List\x12 .objectives.v1alpha1.ListRequest\x1a!.objectives.v1alpha1.ListResponse\"\x00\x12\\\n" +
	"\tGetStatus\x12%.objectives.v1alpha1.GetStatusRequest\x1a&.objectives.v1alpha1.GetStatusResponse\"\x00\x12\\\n" +
	"\tGetAlerts\x12%.objectives.v1alpha1.GetAlertsRequest\x1a&.objectives.v1alpha1.GetAlertsResponse\"\x00\x12q\n" +
	"\x10GraphErrorBudget\x12,.objectives.v1alpha1.GraphErrorBudgetRequest\x1a-.objectives.v1alpha1.GraphErrorBudgetResponse\"\x00\x12\\\n" +
	"\tGraphRate\x12%.objectives.v1alpha1.GraphRateRequest\x1a&.objectives.v1alpha1.GraphRateResponse\"\x00\x12b\n" +
	"\vGraphErrors\x12'.objectives.v1alpha1.GraphErrorsRequest\x1a(.objectives.v1alpha1.GraphErrorsResponse\"\x00\x12h\n" +
	"\rGraphDuration\x12).objectives.v1alpha1.GraphDurationRequest\x1a*.objectives.v1alpha1.GraphDurationResponse\"\x002h\n" +
	"\x17ObjectiveBackendService\x12M\n" +
	"\x04List\x12 .objectives.v1alpha1.ListRequest\x1a!.objectives.v1alpha1.ListResponse\"\x00BIZGgithub.com/pyrra-dev/pyrra/proto/objectives/v1alpha1;objectivesv1alpha1b\x06proto3"

var (
	file_objectives_v1alpha1_objectives_proto_rawDescOnce sync.Once
	file_objectives_v1alpha1_objectives_proto_rawDescData []byte
)

func file_objectives_v1alpha1_objectives_proto_rawDescGZIP() []byte {
	file_objectives_v1alpha1_objectives_proto_rawDescOnce.Do(func() {
		file_objectives_v1alpha1_objectives_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_objectives_v1alpha1_objectives_proto_rawDesc), len(file_objectives_v1alpha1_objectives_proto_rawDesc)))
	})
	return file_objectives_v1alpha1_objectives_proto_rawDescData
}

var file_objectives_v1alpha1_objectives_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_objectives_v1alpha1_objectives_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_objectives_v1alpha1_objectives_proto_goTypes = []any{
	(LabelMatcher_Type)(0),           // 0: objectives.v1alpha1.LabelMatcher.Type
	(Alert_State)(0),                 // 1: objectives.v1alpha1.Alert.State
	(*ListRequest)(nil),              // 2: objectives.v1alpha1.ListRequest
	(*ListResponse)(nil),             // 3: objectives.v1alpha1.ListResponse
	(*Objective)(nil),                // 4: objectives.v1alpha1.Objective
	(*Indicator)(nil),                // 5: objectives.v1alpha1.Indicator
	(*Ratio)(nil),                    // 6: objectives.v1alpha1.Ratio
	(*Latency)(nil),                  // 7: objectives.v1alpha1.Latency
	(*LatencyNative)(nil),            // 8: objectives.v1alpha1.LatencyNative
	(*BoolGauge)(nil),                // 9: objectives.v1alpha1.BoolGauge
	(*Query)(nil),                    // 10: objectives.v1alpha1.Query
	(*Queries)(nil),                  // 11: objectives.v1alpha1.Queries
	(*Alerting)(nil),                 // 12: objectives.v1alpha1.Alerting
	(*LabelMatcher)(nil),             // 13: objectives.v1alpha1.LabelMatcher
	(*GetStatusRequest)(nil),         // 14: objectives.v1alpha1.GetStatusRequest
	(*GetStatusResponse)(nil),        // 15: objectives.v1alpha1.GetStatusResponse
	(*ObjectiveStatus)(nil),          // 16: objectives.v1alpha1.ObjectiveStatus
	(*Availability)(nil),             // 17: objectives.v1alpha1.Availability
	(*Budget)(nil),                   // 18: objectives.v1alpha1.Budget
	(*GetAlertsRequest)(nil),         // 19: objectives.v1alpha1.GetAlertsRequest
	(*GetAlertsResponse)(nil),        // 20: objectives.v1alpha1.GetAlertsResponse
	(*Alert)(nil),                    // 21: objectives.v1alpha1.Alert
	(*Burnrate)(nil),                 // 22: objectives.v1alpha1.Burnrate
	(*GraphErrorBudgetRequest)(nil),  // 23: objectives.v1alpha1.GraphErrorBudgetRequest
	(*GraphErrorBudgetResponse)(nil), // 24: objectives.v1alpha1.GraphErrorBudgetResponse
	(*GraphRateRequest)(nil),         // 25: objectives.v1alpha1.GraphRateRequest
	(*GraphRateResponse)(nil),        // 26: objectives.v1alpha1.GraphRateResponse
	(*GraphErrorsRequest)(nil),       // 27: objectives.v1alpha1.GraphErrorsRequest
	(*GraphErrorsResponse)(nil),      // 28: objectives.v1alpha1.GraphErrorsResponse
	(*Timeseries)(nil),               // 29: objectives.v1alpha1.Timeseries
	(*Series)(nil),                   // 30: objectives.v1alpha1.Series
	(*GraphDurationRequest)(nil),     // 31: objectives.v1alpha1.GraphDurationRequest
	(*GraphDurationResponse)(nil),    // 32: objectives.v1alpha1.GraphDurationResponse
	nil,                              // 33: objectives.v1alpha1.Objective.LabelsEntry
	nil,                              // 34: objectives.v1alpha1.ObjectiveStatus.LabelsEntry
	nil,                              // 35: objectives.v1alpha1.Alert.LabelsEntry
	(*durationpb.Duration)(nil),      // 36: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),    // 37: google.protobuf.Timestamp
}
var file_objectives_v1alpha1_objectives_proto_depIdxs = []int32{
	4,  // 0: objectives.v1alpha1.ListResponse.objectives:type_name -> objectives.v1alpha1.Objective
	33, // 1: objectives.v1alpha1.Objective.labels:type_name -> objectives.v1alpha1.Objective.LabelsEntry
	36, // 2: objectives.v1alpha1.Objective.window:type_name -> google.protobuf.Duration
	5,  // 3: objectives.v1alpha1.Objective.indicator:type_name -> objectives.v1alpha1.Indicator
	11, // 4: objectives.v1alpha1.Objective.queries:type_name -> objectives.v1alpha1.Queries
	12, // 5: objectives.v1alpha1.Objective.alerting:type_name -> objectives.v1alpha1.Alerting
	6,  // 6: objectives.v1alpha1.Indicator.ratio:type_name -> objectives.v1alpha1.Ratio
	7,  // 7: objectives.v1alpha1.Indicator.latency:type_name -> objectives.v1alpha1.Latency
	9,  // 8: objectives.v1alpha1.Indicator.boolGauge:type_name -> objectives.v1alpha1.BoolGauge
	8,  // 9: objectives.v1alpha1.Indicator.latency_native:type_name -> objectives.v1alpha1.LatencyNative
	10, // 10: objectives.v1alpha1.Ratio.total:type_name -> objectives.v1alpha1.Query
	10, // 11: objectives.v1alpha1.Ratio.errors:type_name -> objectives.v1alpha1.Query
	10, // 12: objectives.v1alpha1.Latency.total:type_name -> objectives.v1alpha1.Query
	10, // 13: objectives.v1alpha1.Latency.success:type_name -> objectives.v1alpha1.Query
	10, // 14: objectives.v1alpha1.LatencyNative.total:type_name -> objectives.v1alpha1.Query
	10, // 15: objectives.v1alpha1.BoolGauge.boolGauge:type_name -> objectives.v1alpha1.Query
	13, // 16: objectives.v1alpha1.Query.matchers:type_name -> objectives.v1alpha1.LabelMatcher
	0,  // 17: objectives.v1alpha1.LabelMatcher.type:type_name -> objectives.v1alpha1.LabelMatcher.Type
	37, // 18: objectives.v1alpha1.GetStatusRequest.time:type_name -> google.protobuf.Timestamp
	16, // 19: objectives.v1alpha1.GetStatusResponse.status:type_name -> objectives.v1alpha1.ObjectiveStatus
	34, // 20: objectives.v1alpha1.ObjectiveStatus.labels:type_name -> objectives.v1alpha1.ObjectiveStatus.LabelsEntry
	17, // 21: objectives.v1alpha1.ObjectiveStatus.availability:type_name -> objectives.v1alpha1.Availability
	18, // 22: objectives.v1alpha1.ObjectiveStatus.budget:type_name -> objectives.v1alpha1.Budget
	21, // 23: objectives.v1alpha1.GetAlertsResponse.alerts:type_name -> objectives.v1alpha1.Alert
	35, // 24: objectives.v1alpha1.Alert.labels:type_name -> objectives.v1alpha1.Alert.LabelsEntry
	36, // 25: objectives.v1alpha1.Alert.for:type_name -> google.protobuf.Duration
	1,  // 26: objectives.v1alpha1.Alert.state:type_name -> objectives.v1alpha1.Alert.State
	22, // 27: objectives.v1alpha1.Alert.short:type_name -> objectives.v1alpha1.Burnrate
	22, // 28: objectives.v1alpha1.Alert.long:type_name -> objectives.v1alpha1.Burnrate
	36, // 29: objectives.v1alpha1.Burnrate.window:type_name -> google.protobuf.Duration
	37, // 30: objectives.v1alpha1.GraphErrorBudgetRequest.start:type_name -> google.protobuf.Timestamp
	37, // 31: objectives.v1alpha1.GraphErrorBudgetRequest.end:type_name -> google.protobuf.Timestamp
	29, // 32: objectives.v1alpha1.GraphErrorBudgetResponse.timeseries:type_name -> objectives.v1alpha1.Timeseries
	37, // 33: objectives.v1alpha1.GraphRateRequest.start:type_name -> google.protobuf.Timestamp
	37, // 34: objectives.v1alpha1.GraphRateRequest.end:type_name -> google.protobuf.Timestamp
	29, // 35: objectives.v1alpha1.GraphRateResponse.timeseries:type_name -> objectives.v1alpha1.Timeseries
	37, // 36: objectives.v1alpha1.GraphErrorsRequest.start:type_name -> google.protobuf.Timestamp
	37, // 37: objectives.v1alpha1.GraphErrorsRequest.end:type_name -> google.protobuf.Timestamp
	29, // 38: objectives.v1alpha1.GraphErrorsResponse.timeseries:type_name -> objectives.v1alpha1.Timeseries
	30, // 39: objectives.v1alpha1.Timeseries.series:type_name -> objectives.v1alpha1.Series
	37, // 40: objectives.v1alpha1.GraphDurationRequest.start:type_name -> google.protobuf.Timestamp
	37, // 41: objectives.v1alpha1.GraphDurationRequest.end:type_name -> google.protobuf.Timestamp
	29, // 42: objectives.v1alpha1.GraphDurationResponse.timeseries:type_name -> objectives.v1alpha1.Timeseries
	2,  // 43: objectives.v1alpha1.ObjectiveService.List:input_type -> objectives.v1alpha1.ListRequest
	14, // 44: objectives.v1alpha1.ObjectiveService.GetStatus:input_type -> objectives.v1alpha1.GetStatusRequest
	19, // 45: objectives.v1alpha1.ObjectiveService.GetAlerts:input_type -> objectives.v1alpha1.GetAlertsRequest
	23, // 46: objectives.v1alpha1.ObjectiveService.GraphErrorBudget:input_type -> objectives.v1alpha1.GraphErrorBudgetRequest
	25, // 47: objectives.v1alpha1.ObjectiveService.GraphRate:input_type -> objectives.v1alpha1.GraphRateRequest
	27, // 48: objectives.v1alpha1.ObjectiveService.GraphErrors:input_type -> objectives.v1alpha1.GraphErrorsRequest
	31, // 49: objectives.v1alpha1.ObjectiveService.GraphDuration:input_type -> objectives.v1alpha1.GraphDurationRequest
	2,  // 50: objectives.v1alpha1.ObjectiveBackendService.List:input_type -> objectives.v1alpha1.ListRequest
	3,  // 51: objectives.v1alpha1.ObjectiveService.List:output_type -> objectives.v1alpha1.ListResponse
	15, // 52: objectives.v1alpha1.ObjectiveService.GetStatus:output_type -> objectives.v1alpha1.GetStatusResponse
	20, // 53: objectives.v1alpha1.ObjectiveService.GetAlerts:output_type -> objectives.v1alpha1.GetAlertsResponse
	24, // 54: objectives.v1alpha1.ObjectiveService.GraphErrorBudget:output_type -> objectives.v1alpha1.GraphErrorBudgetResponse
	26, // 55: objectives.v1alpha1.ObjectiveService.GraphRate:output_type -> objectives.v1alpha1.GraphRateResponse
	28, // 56: objectives.v1alpha1.ObjectiveService.GraphErrors:output_type -> objectives.v1alpha1.GraphErrorsResponse
	32, // 57: objectives.v1alpha1.ObjectiveService.GraphDuration:output_type -> objectives.v1alpha1.GraphDurationResponse
	3,  // 58: objectives.v1alpha1.ObjectiveBackendService.List:output_type -> objectives.v1alpha1.ListResponse
	51, // [51:59] is the sub-list for method output_type
	43, // [43:51] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_objectives_v1alpha1_objectives_proto_init() }
func file_objectives_v1alpha1_objectives_proto_init() {
	if File_objectives_v1alpha1_objectives_proto != nil {
		return
	}
	file_objectives_v1alpha1_objectives_proto_msgTypes[3].OneofWrappers = []any{
		(*Indicator_Ratio)(nil),
		(*Indicator_Latency)(nil),
		(*Indicator_BoolGauge)(nil),
		(*Indicator_LatencyNative)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_objectives_v1alpha1_objectives_proto_rawDesc), len(file_objectives_v1alpha1_objectives_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_objectives_v1alpha1_objectives_proto_goTypes,
		DependencyIndexes: file_objectives_v1alpha1_objectives_proto_depIdxs,
		EnumInfos:         file_objectives_v1alpha1_objectives_proto_enumTypes,
		MessageInfos:      file_objectives_v1alpha1_objectives_proto_msgTypes,
	}.Build()
	File_objectives_v1alpha1_objectives_proto = out.File
	file_objectives_v1alpha1_objectives_proto_goTypes = nil
	file_objectives_v1alpha1_objectives_proto_depIdxs = nil
}
