# Test Dynamic Burn Rate SLO
# Uses apiserver_request_total which has real error data for validation
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: test-dynamic-apiserver
  namespace: monitoring
  labels:
    app: dynamic-testing
    component: apiserver
spec:
  target: "95"
  window: 30d
  description: "Dynamic burn rate test SLO using apiserver requests - GET operations"
  indicator:
    ratio:
      errors:
        metric: apiserver_request_total{verb="GET",code=~"4..|5.."}
      total:
        metric: apiserver_request_total{verb="GET"}
  alerting:
    name: TestDynamicApiserver
    burnRateType: dynamic  # Enable dynamic burn rates
    burnrates: true
    absent: true
