// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: objectives/v1alpha1/objectives.proto

package objectivesv1alpha1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1alpha1 "github.com/pyrra-dev/pyrra/proto/objectives/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ObjectiveServiceName is the fully-qualified name of the ObjectiveService service.
	ObjectiveServiceName = "objectives.v1alpha1.ObjectiveService"
	// ObjectiveBackendServiceName is the fully-qualified name of the ObjectiveBackendService service.
	ObjectiveBackendServiceName = "objectives.v1alpha1.ObjectiveBackendService"
)

// ObjectiveServiceClient is a client for the objectives.v1alpha1.ObjectiveService service.
type ObjectiveServiceClient interface {
	ListObjectives(context.Context, *connect_go.Request[v1alpha1.ListObjectivesRequest]) (*connect_go.Response[v1alpha1.ListObjectivesResponse], error)
}

// NewObjectiveServiceClient constructs a client for the objectives.v1alpha1.ObjectiveService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewObjectiveServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ObjectiveServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &objectiveServiceClient{
		listObjectives: connect_go.NewClient[v1alpha1.ListObjectivesRequest, v1alpha1.ListObjectivesResponse](
			httpClient,
			baseURL+"/objectives.v1alpha1.ObjectiveService/ListObjectives",
			opts...,
		),
	}
}

// objectiveServiceClient implements ObjectiveServiceClient.
type objectiveServiceClient struct {
	listObjectives *connect_go.Client[v1alpha1.ListObjectivesRequest, v1alpha1.ListObjectivesResponse]
}

// ListObjectives calls objectives.v1alpha1.ObjectiveService.ListObjectives.
func (c *objectiveServiceClient) ListObjectives(ctx context.Context, req *connect_go.Request[v1alpha1.ListObjectivesRequest]) (*connect_go.Response[v1alpha1.ListObjectivesResponse], error) {
	return c.listObjectives.CallUnary(ctx, req)
}

// ObjectiveServiceHandler is an implementation of the objectives.v1alpha1.ObjectiveService service.
type ObjectiveServiceHandler interface {
	ListObjectives(context.Context, *connect_go.Request[v1alpha1.ListObjectivesRequest]) (*connect_go.Response[v1alpha1.ListObjectivesResponse], error)
}

// NewObjectiveServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewObjectiveServiceHandler(svc ObjectiveServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/objectives.v1alpha1.ObjectiveService/ListObjectives", connect_go.NewUnaryHandler(
		"/objectives.v1alpha1.ObjectiveService/ListObjectives",
		svc.ListObjectives,
		opts...,
	))
	return "/objectives.v1alpha1.ObjectiveService/", mux
}

// UnimplementedObjectiveServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedObjectiveServiceHandler struct{}

func (UnimplementedObjectiveServiceHandler) ListObjectives(context.Context, *connect_go.Request[v1alpha1.ListObjectivesRequest]) (*connect_go.Response[v1alpha1.ListObjectivesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("objectives.v1alpha1.ObjectiveService.ListObjectives is not implemented"))
}

// ObjectiveBackendServiceClient is a client for the objectives.v1alpha1.ObjectiveBackendService
// service.
type ObjectiveBackendServiceClient interface {
	ListObjectives(context.Context, *connect_go.Request[v1alpha1.ListObjectivesRequest]) (*connect_go.Response[v1alpha1.ListObjectivesResponse], error)
}

// NewObjectiveBackendServiceClient constructs a client for the
// objectives.v1alpha1.ObjectiveBackendService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewObjectiveBackendServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ObjectiveBackendServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &objectiveBackendServiceClient{
		listObjectives: connect_go.NewClient[v1alpha1.ListObjectivesRequest, v1alpha1.ListObjectivesResponse](
			httpClient,
			baseURL+"/objectives.v1alpha1.ObjectiveBackendService/ListObjectives",
			opts...,
		),
	}
}

// objectiveBackendServiceClient implements ObjectiveBackendServiceClient.
type objectiveBackendServiceClient struct {
	listObjectives *connect_go.Client[v1alpha1.ListObjectivesRequest, v1alpha1.ListObjectivesResponse]
}

// ListObjectives calls objectives.v1alpha1.ObjectiveBackendService.ListObjectives.
func (c *objectiveBackendServiceClient) ListObjectives(ctx context.Context, req *connect_go.Request[v1alpha1.ListObjectivesRequest]) (*connect_go.Response[v1alpha1.ListObjectivesResponse], error) {
	return c.listObjectives.CallUnary(ctx, req)
}

// ObjectiveBackendServiceHandler is an implementation of the
// objectives.v1alpha1.ObjectiveBackendService service.
type ObjectiveBackendServiceHandler interface {
	ListObjectives(context.Context, *connect_go.Request[v1alpha1.ListObjectivesRequest]) (*connect_go.Response[v1alpha1.ListObjectivesResponse], error)
}

// NewObjectiveBackendServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewObjectiveBackendServiceHandler(svc ObjectiveBackendServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/objectives.v1alpha1.ObjectiveBackendService/ListObjectives", connect_go.NewUnaryHandler(
		"/objectives.v1alpha1.ObjectiveBackendService/ListObjectives",
		svc.ListObjectives,
		opts...,
	))
	return "/objectives.v1alpha1.ObjectiveBackendService/", mux
}

// UnimplementedObjectiveBackendServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedObjectiveBackendServiceHandler struct{}

func (UnimplementedObjectiveBackendServiceHandler) ListObjectives(context.Context, *connect_go.Request[v1alpha1.ListObjectivesRequest]) (*connect_go.Response[v1alpha1.ListObjectivesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("objectives.v1alpha1.ObjectiveBackendService.ListObjectives is not implemented"))
}
