// @generated by protoc-gen-connect-web v0.8.1 with parameter "target=js+dts"
// @generated from file prometheus/v1/prometheus.proto (package prometheus.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryRangeRequest, QueryRangeResponse, QueryRequest, QueryResponse } from "./prometheus_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service prometheus.v1.PrometheusService
 */
export declare const PrometheusService: {
  readonly typeName: "prometheus.v1.PrometheusService",
  readonly methods: {
    /**
     * @generated from rpc prometheus.v1.PrometheusService.Query
     */
    readonly query: {
      readonly name: "Query",
      readonly I: typeof QueryRequest,
      readonly O: typeof QueryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc prometheus.v1.PrometheusService.QueryRange
     */
    readonly queryRange: {
      readonly name: "QueryRange",
      readonly I: typeof QueryRangeRequest,
      readonly O: typeof QueryRangeResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

