apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: synthetic-alert-test-dynamic
  namespace: monitoring
  labels:
    pyrra.dev/team: testing
spec:
  target: "95"
  window: 1d
  description: "Dynamic burn rate SLO for synthetic alert testing - 1d window gives ~2.1min alert windows"
  alerting:
    burnRateType: dynamic
    burnrates: true
    absent: true
    name: SyntheticAlertTestDynamic
  indicator:
    ratio:
      errors:
        metric: synthetic_test_requests_error_total{service="synthetic-alert-test"}
      total:
        metric: synthetic_test_requests_total{service="synthetic-alert-test"}
---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: synthetic-alert-test-static
  namespace: monitoring
  labels:
    pyrra.dev/team: testing
spec:
  target: "95"
  window: 1d
  description: "Static burn rate SLO for synthetic alert testing comparison - 1d window gives ~2.1min alert windows"
  alerting:
    burnrates: true
    absent: true
    name: SyntheticAlertTestStatic
  indicator:
    ratio:
      errors:
        metric: synthetic_test_requests_error_total{service="synthetic-alert-test"}
      total:
        metric: synthetic_test_requests_total{service="synthetic-alert-test"}