/*
 * Pyrra
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QueryMatchers struct {
	Name string `json:"name,omitempty"`

	Value string `json:"value,omitempty"`

	Type int32 `json:"type,omitempty"`
}
