/*
 * Athene
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QueryRange struct {
	Query string `json:"query"`

	Labels []string `json:"labels"`

	Values [][]float64 `json:"values"`
}
