// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: prometheus/v1/prometheus.proto

package prometheusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type QueryResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Warnings []string               `protobuf:"bytes,1,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Types that are valid to be assigned to Options:
	//
	//	*QueryResponse_Scalar
	//	*QueryResponse_Vector
	//	*QueryResponse_Matrix
	//	*QueryResponse_String_
	Options       isQueryResponse_Options `protobuf_oneof:"options"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *QueryResponse) GetOptions() isQueryResponse_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QueryResponse) GetScalar() *SamplePair {
	if x != nil {
		if x, ok := x.Options.(*QueryResponse_Scalar); ok {
			return x.Scalar
		}
	}
	return nil
}

func (x *QueryResponse) GetVector() *Vector {
	if x != nil {
		if x, ok := x.Options.(*QueryResponse_Vector); ok {
			return x.Vector
		}
	}
	return nil
}

func (x *QueryResponse) GetMatrix() *Matrix {
	if x != nil {
		if x, ok := x.Options.(*QueryResponse_Matrix); ok {
			return x.Matrix
		}
	}
	return nil
}

func (x *QueryResponse) GetString_() *String {
	if x != nil {
		if x, ok := x.Options.(*QueryResponse_String_); ok {
			return x.String_
		}
	}
	return nil
}

type isQueryResponse_Options interface {
	isQueryResponse_Options()
}

type QueryResponse_Scalar struct {
	Scalar *SamplePair `protobuf:"bytes,2,opt,name=scalar,proto3,oneof"`
}

type QueryResponse_Vector struct {
	Vector *Vector `protobuf:"bytes,3,opt,name=vector,proto3,oneof"`
}

type QueryResponse_Matrix struct {
	Matrix *Matrix `protobuf:"bytes,4,opt,name=matrix,proto3,oneof"`
}

type QueryResponse_String_ struct {
	String_ *String `protobuf:"bytes,5,opt,name=string,proto3,oneof"`
}

func (*QueryResponse_Scalar) isQueryResponse_Options() {}

func (*QueryResponse_Vector) isQueryResponse_Options() {}

func (*QueryResponse_Matrix) isQueryResponse_Options() {}

func (*QueryResponse_String_) isQueryResponse_Options() {}

type QueryRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Step          int64                  `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRangeRequest) Reset() {
	*x = QueryRangeRequest{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeRequest) ProtoMessage() {}

func (x *QueryRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeRequest.ProtoReflect.Descriptor instead.
func (*QueryRangeRequest) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRangeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRangeRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *QueryRangeRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *QueryRangeRequest) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

type QueryRangeResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Warnings []string               `protobuf:"bytes,1,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Types that are valid to be assigned to Options:
	//
	//	*QueryRangeResponse_Scalar
	//	*QueryRangeResponse_Vector
	//	*QueryRangeResponse_Matrix
	//	*QueryRangeResponse_String_
	Options       isQueryRangeResponse_Options `protobuf_oneof:"options"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRangeResponse) Reset() {
	*x = QueryRangeResponse{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeResponse) ProtoMessage() {}

func (x *QueryRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeResponse.ProtoReflect.Descriptor instead.
func (*QueryRangeResponse) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRangeResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *QueryRangeResponse) GetOptions() isQueryRangeResponse_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QueryRangeResponse) GetScalar() *SamplePair {
	if x != nil {
		if x, ok := x.Options.(*QueryRangeResponse_Scalar); ok {
			return x.Scalar
		}
	}
	return nil
}

func (x *QueryRangeResponse) GetVector() *Vector {
	if x != nil {
		if x, ok := x.Options.(*QueryRangeResponse_Vector); ok {
			return x.Vector
		}
	}
	return nil
}

func (x *QueryRangeResponse) GetMatrix() *Matrix {
	if x != nil {
		if x, ok := x.Options.(*QueryRangeResponse_Matrix); ok {
			return x.Matrix
		}
	}
	return nil
}

func (x *QueryRangeResponse) GetString_() *String {
	if x != nil {
		if x, ok := x.Options.(*QueryRangeResponse_String_); ok {
			return x.String_
		}
	}
	return nil
}

type isQueryRangeResponse_Options interface {
	isQueryRangeResponse_Options()
}

type QueryRangeResponse_Scalar struct {
	Scalar *SamplePair `protobuf:"bytes,2,opt,name=scalar,proto3,oneof"`
}

type QueryRangeResponse_Vector struct {
	Vector *Vector `protobuf:"bytes,3,opt,name=vector,proto3,oneof"`
}

type QueryRangeResponse_Matrix struct {
	Matrix *Matrix `protobuf:"bytes,4,opt,name=matrix,proto3,oneof"`
}

type QueryRangeResponse_String_ struct {
	String_ *String `protobuf:"bytes,5,opt,name=string,proto3,oneof"`
}

func (*QueryRangeResponse_Scalar) isQueryRangeResponse_Options() {}

func (*QueryRangeResponse_Vector) isQueryRangeResponse_Options() {}

func (*QueryRangeResponse_Matrix) isQueryRangeResponse_Options() {}

func (*QueryRangeResponse_String_) isQueryRangeResponse_Options() {}

// Vector is basically only an alias for Samples, but the
// contract is that in a Vector, all Samples have the same timestamp.
type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*Sample              `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{4}
}

func (x *Vector) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

// Sample is a sample pair associated with a metric.
type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Metric        map[string]string      `protobuf:"bytes,3,rep,name=metric,proto3" json:"metric,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{5}
}

func (x *Sample) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Sample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Sample) GetMetric() map[string]string {
	if x != nil {
		return x.Metric
	}
	return nil
}

// Matrix is a list of time series.
type Matrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*SampleStream        `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix) Reset() {
	*x = Matrix{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix) ProtoMessage() {}

func (x *Matrix) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix.ProtoReflect.Descriptor instead.
func (*Matrix) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{6}
}

func (x *Matrix) GetSamples() []*SampleStream {
	if x != nil {
		return x.Samples
	}
	return nil
}

// SampleStream is a stream of Values belonging to an attached COWMetric.
type SampleStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*SamplePair          `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Metric        map[string]string      `protobuf:"bytes,2,rep,name=metric,proto3" json:"metric,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleStream) Reset() {
	*x = SampleStream{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleStream) ProtoMessage() {}

func (x *SampleStream) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleStream.ProtoReflect.Descriptor instead.
func (*SampleStream) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{7}
}

func (x *SampleStream) GetValues() []*SamplePair {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SampleStream) GetMetric() map[string]string {
	if x != nil {
		return x.Metric
	}
	return nil
}

// SamplePair pairs a SampleValue with a Timestamp.
type SamplePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplePair) Reset() {
	*x = SamplePair{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplePair) ProtoMessage() {}

func (x *SamplePair) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplePair.ProtoReflect.Descriptor instead.
func (*SamplePair) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{8}
}

func (x *SamplePair) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SamplePair) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// String is a string value evaluated at the set timestamp.
type String struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *String) Reset() {
	*x = String{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{9}
}

func (x *String) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LabelNamesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// matchers optionally scopes label names to series matching these
	// selectors, e.g. {__name__="http_requests_total"}.
	Matchers []string `protobuf:"bytes,1,rep,name=matchers,proto3" json:"matchers,omitempty"`
	// start and end bound the discovery window as unix seconds. 0 means
	// unbounded, matching Prometheus' own UI behavior for these endpoints.
	Start         int64 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           int64 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelNamesRequest) Reset() {
	*x = LabelNamesRequest{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelNamesRequest) ProtoMessage() {}

func (x *LabelNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelNamesRequest.ProtoReflect.Descriptor instead.
func (*LabelNamesRequest) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{10}
}

func (x *LabelNamesRequest) GetMatchers() []string {
	if x != nil {
		return x.Matchers
	}
	return nil
}

func (x *LabelNamesRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LabelNamesRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type LabelNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelNamesResponse) Reset() {
	*x = LabelNamesResponse{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelNamesResponse) ProtoMessage() {}

func (x *LabelNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelNamesResponse.ProtoReflect.Descriptor instead.
func (*LabelNamesResponse) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{11}
}

func (x *LabelNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *LabelNamesResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type LabelValuesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label is the label name to list values for. "__name__" lists metric names.
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// matchers optionally scopes label values to series matching these
	// selectors, e.g. {__name__="http_requests_total"}.
	Matchers []string `protobuf:"bytes,2,rep,name=matchers,proto3" json:"matchers,omitempty"`
	// start and end bound the discovery window as unix seconds. 0 means
	// unbounded, matching Prometheus' own UI behavior for these endpoints.
	Start         int64 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End           int64 `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelValuesRequest) Reset() {
	*x = LabelValuesRequest{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelValuesRequest) ProtoMessage() {}

func (x *LabelValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelValuesRequest.ProtoReflect.Descriptor instead.
func (*LabelValuesRequest) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{12}
}

func (x *LabelValuesRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabelValuesRequest) GetMatchers() []string {
	if x != nil {
		return x.Matchers
	}
	return nil
}

func (x *LabelValuesRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LabelValuesRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type LabelValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelValuesResponse) Reset() {
	*x = LabelValuesResponse{}
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelValuesResponse) ProtoMessage() {}

func (x *LabelValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_v1_prometheus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelValuesResponse.ProtoReflect.Descriptor instead.
func (*LabelValuesResponse) Descriptor() ([]byte, []int) {
	return file_prometheus_v1_prometheus_proto_rawDescGZIP(), []int{13}
}

func (x *LabelValuesResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *LabelValuesResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_prometheus_v1_prometheus_proto protoreflect.FileDescriptor

const file_prometheus_v1_prometheus_proto_rawDesc = "" +
	"\n" +
	"\x1eprometheus/v1/prometheus.proto\x12\rprometheus.v1\"8\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\"\xfe\x01\n" +
	"\rQueryResponse\x12\x1a\n" +
	"\bwarnings\x18\x01 \x03(\tR\bwarnings\x123\n" +
	"\x06scalar\x18\x02 \x01(\v2\x19.prometheus.v1.SamplePairH\x00R\x06scalar\x12/\n" +
	"\x06vector\x18\x03 \x01(\v2\x15.prometheus.v1.VectorH\x00R\x06vector\x12/\n" +
	"\x06matrix\x18\x04 \x01(\v2\x15.prometheus.v1.MatrixH\x00R\x06matrix\x12/\n" +
	"\x06string\x18\x05 \x01(\v2\x15.prometheus.v1.StringH\x00R\x06stringB\t\n" +
	"\aoptions\"e\n" +
	"\x11QueryRangeRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x03R\x03end\x12\x12\n" +
	"\x04step\x18\x04 \x01(\x03R\x04step\"\x83\x02\n" +
	"\x12QueryRangeResponse\x12\x1a\n" +
	"\bwarnings\x18\x01 \x03(\tR\bwarnings\x123\n" +
	"\x06scalar\x18\x02 \x01(\v2\x19.prometheus.v1.SamplePairH\x00R\x06scalar\x12/\n" +
	"\x06vector\x18\x03 \x01(\v2\x15.prometheus.v1.VectorH\x00R\x06vector\x12/\n" +
	"\x06matrix\x18\x04 \x01(\v2\x15.prometheus.v1.MatrixH\x00R\x06matrix\x12/\n" +
	"\x06string\x18\x05 \x01(\v2\x15.prometheus.v1.StringH\x00R\x06stringB\t\n" +
	"\aoptions\"9\n" +
	"\x06Vector\x12/\n" +
	"\asamples\x18\x01 \x03(\v2\x15.prometheus.v1.SampleR\asamples\"\xa8\x01\n" +
	"\x06Sample\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x129\n" +
	"\x06metric\x18\x03 \x03(\v2!.prometheus.v1.Sample.MetricEntryR\x06metric\x1a9\n" +
	"\vMetricEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x06Matrix\x125\n" +
	"\asamples\x18\x01 \x03(\v2\x1b.prometheus.v1.SampleStreamR\asamples\"\xbd\x01\n" +
	"\fSampleStream\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.prometheus.v1.SamplePairR\x06values\x12?\n" +
	"\x06metric\x18\x02 \x03(\v2'.prometheus.v1.SampleStream.MetricEntryR\x06metric\x1a9\n" +
	"\vMetricEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\n" +
	"SamplePair\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"2\n" +
	"\x06String\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"W\n" +
	"\x11LabelNamesRequest\x12\x1a\n" +
	"\bmatchers\x18\x01 \x03(\tR\bmatchers\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x03R\x03end\"F\n" +
	"\x12LabelNamesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\"n\n" +
	"\x12LabelValuesRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1a\n" +
	"\bmatchers\x18\x02 \x03(\tR\bmatchers\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x03R\x03end\"I\n" +
	"\x13LabelValuesResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings2\xdb\x02\n" +
	"\x11PrometheusService\x12D\n" +
	"\x05Query\x12\x1b.prometheus.v1.QueryRequest\x1a\x1c.prometheus.v1.QueryResponse\"\x00\x12S\n" +
	"\n" +
	"QueryRange\x12 .prometheus.v1.QueryRangeRequest\x1a!.prometheus.v1.QueryRangeResponse\"\x00\x12S\n" +
	"\n" +
	"LabelNames\x12 .prometheus.v1.LabelNamesRequest\x1a!.prometheus.v1.LabelNamesResponse\"\x00\x12V\n" +
	"\vLabelValues\x12!.prometheus.v1.LabelValuesRequest\x1a\".prometheus.v1.LabelValuesResponse\"\x00B=Z;github.com/pyrra-dev/pyrra/proto/prometheus/v1;prometheusv1b\x06proto3"

var (
	file_prometheus_v1_prometheus_proto_rawDescOnce sync.Once
	file_prometheus_v1_prometheus_proto_rawDescData []byte
)

func file_prometheus_v1_prometheus_proto_rawDescGZIP() []byte {
	file_prometheus_v1_prometheus_proto_rawDescOnce.Do(func() {
		file_prometheus_v1_prometheus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prometheus_v1_prometheus_proto_rawDesc), len(file_prometheus_v1_prometheus_proto_rawDesc)))
	})
	return file_prometheus_v1_prometheus_proto_rawDescData
}

var file_prometheus_v1_prometheus_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_prometheus_v1_prometheus_proto_goTypes = []any{
	(*QueryRequest)(nil),        // 0: prometheus.v1.QueryRequest
	(*QueryResponse)(nil),       // 1: prometheus.v1.QueryResponse
	(*QueryRangeRequest)(nil),   // 2: prometheus.v1.QueryRangeRequest
	(*QueryRangeResponse)(nil),  // 3: prometheus.v1.QueryRangeResponse
	(*Vector)(nil),              // 4: prometheus.v1.Vector
	(*Sample)(nil),              // 5: prometheus.v1.Sample
	(*Matrix)(nil),              // 6: prometheus.v1.Matrix
	(*SampleStream)(nil),        // 7: prometheus.v1.SampleStream
	(*SamplePair)(nil),          // 8: prometheus.v1.SamplePair
	(*String)(nil),              // 9: prometheus.v1.String
	(*LabelNamesRequest)(nil),   // 10: prometheus.v1.LabelNamesRequest
	(*LabelNamesResponse)(nil),  // 11: prometheus.v1.LabelNamesResponse
	(*LabelValuesRequest)(nil),  // 12: prometheus.v1.LabelValuesRequest
	(*LabelValuesResponse)(nil), // 13: prometheus.v1.LabelValuesResponse
	nil,                         // 14: prometheus.v1.Sample.MetricEntry
	nil,                         // 15: prometheus.v1.SampleStream.MetricEntry
}
var file_prometheus_v1_prometheus_proto_depIdxs = []int32{
	8,  // 0: prometheus.v1.QueryResponse.scalar:type_name -> prometheus.v1.SamplePair
	4,  // 1: prometheus.v1.QueryResponse.vector:type_name -> prometheus.v1.Vector
	6,  // 2: prometheus.v1.QueryResponse.matrix:type_name -> prometheus.v1.Matrix
	9,  // 3: prometheus.v1.QueryResponse.string:type_name -> prometheus.v1.String
	8,  // 4: prometheus.v1.QueryRangeResponse.scalar:type_name -> prometheus.v1.SamplePair
	4,  // 5: prometheus.v1.QueryRangeResponse.vector:type_name -> prometheus.v1.Vector
	6,  // 6: prometheus.v1.QueryRangeResponse.matrix:type_name -> prometheus.v1.Matrix
	9,  // 7: prometheus.v1.QueryRangeResponse.string:type_name -> prometheus.v1.String
	5,  // 8: prometheus.v1.Vector.samples:type_name -> prometheus.v1.Sample
	14, // 9: prometheus.v1.Sample.metric:type_name -> prometheus.v1.Sample.MetricEntry
	7,  // 10: prometheus.v1.Matrix.samples:type_name -> prometheus.v1.SampleStream
	8,  // 11: prometheus.v1.SampleStream.values:type_name -> prometheus.v1.SamplePair
	15, // 12: prometheus.v1.SampleStream.metric:type_name -> prometheus.v1.SampleStream.MetricEntry
	0,  // 13: prometheus.v1.PrometheusService.Query:input_type -> prometheus.v1.QueryRequest
	2,  // 14: prometheus.v1.PrometheusService.QueryRange:input_type -> prometheus.v1.QueryRangeRequest
	10, // 15: prometheus.v1.PrometheusService.LabelNames:input_type -> prometheus.v1.LabelNamesRequest
	12, // 16: prometheus.v1.PrometheusService.LabelValues:input_type -> prometheus.v1.LabelValuesRequest
	1,  // 17: prometheus.v1.PrometheusService.Query:output_type -> prometheus.v1.QueryResponse
	3,  // 18: prometheus.v1.PrometheusService.QueryRange:output_type -> prometheus.v1.QueryRangeResponse
	11, // 19: prometheus.v1.PrometheusService.LabelNames:output_type -> prometheus.v1.LabelNamesResponse
	13, // 20: prometheus.v1.PrometheusService.LabelValues:output_type -> prometheus.v1.LabelValuesResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_prometheus_v1_prometheus_proto_init() }
func file_prometheus_v1_prometheus_proto_init() {
	if File_prometheus_v1_prometheus_proto != nil {
		return
	}
	file_prometheus_v1_prometheus_proto_msgTypes[1].OneofWrappers = []any{
		(*QueryResponse_Scalar)(nil),
		(*QueryResponse_Vector)(nil),
		(*QueryResponse_Matrix)(nil),
		(*QueryResponse_String_)(nil),
	}
	file_prometheus_v1_prometheus_proto_msgTypes[3].OneofWrappers = []any{
		(*QueryRangeResponse_Scalar)(nil),
		(*QueryRangeResponse_Vector)(nil),
		(*QueryRangeResponse_Matrix)(nil),
		(*QueryRangeResponse_String_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prometheus_v1_prometheus_proto_rawDesc), len(file_prometheus_v1_prometheus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prometheus_v1_prometheus_proto_goTypes,
		DependencyIndexes: file_prometheus_v1_prometheus_proto_depIdxs,
		MessageInfos:      file_prometheus_v1_prometheus_proto_msgTypes,
	}.Build()
	File_prometheus_v1_prometheus_proto = out.File
	file_prometheus_v1_prometheus_proto_goTypes = nil
	file_prometheus_v1_prometheus_proto_depIdxs = nil
}
