# Example SLO with Dynamic Burn Rate
# This demonstrates the new dynamic burn rate feature for traffic-aware alerting
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: api-latency-dynamic-demo
  namespace: monitoring
  labels:
    app: demo-service
    component: api
spec:
  target: 99.5
  window: 30d
  description: "Dynamic burn rate demo for API latency SLO - adapts alert thresholds based on traffic volume"
  indicator:
    latency:
      success:
        metric: http_request_duration_seconds_bucket
        matchers:
        - name: job
          value: api-service
        - name: le
          value: "0.5"
      total:
        metric: http_request_duration_seconds_count  
        matchers:
        - name: job
          value: api-service
  alerting:
    name: ApiLatencyDynamicBurnRate
    burnRateType: dynamic  # Enable dynamic burn rates
    burnrates: true
    absent: true
---
# Comparison SLO with Static Burn Rate
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: api-latency-static-demo
  namespace: monitoring
  labels:
    app: demo-service
    component: api
spec:
  target: 99.5
  window: 30d
  description: "Static burn rate demo for API latency SLO - uses traditional fixed thresholds"
  indicator:
    latency:
      success:
        metric: http_request_duration_seconds_bucket
        matchers:
        - name: job
          value: api-service-static
        - name: le
          value: "0.5"
      total:
        metric: http_request_duration_seconds_count  
        matchers:
        - name: job
          value: api-service-static
  alerting:
    name: ApiLatencyStaticBurnRate
    burnRateType: static   # Traditional static burn rates
    burnrates: true
    absent: true
