apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: demo-dynamic-api
  namespace: monitoring
  labels:
    app: dynamic-demo
spec:
  target: "99.5"
  window: 30d
  description: "Dynamic burn rate demo for API service"
  indicator:
    ratio:
      errors:
        metric: "http_requests_total{job=\"api-service\",code=~\"5..\"}"
      total:
        metric: "http_requests_total{job=\"api-service\"}"
  alerting:
    burnrates: true
    absent: true
---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: demo-static-api
  namespace: monitoring  
  labels:
    app: static-demo
spec:
  target: "99.5"
  window: 30d
  description: "Static burn rate demo for API service"
  indicator:
    ratio:
      errors:
        metric: "http_requests_total{job=\"api-service-static\",code=~\"5..\"}"
      total:
        metric: "http_requests_total{job=\"api-service-static\"}"
  alerting:
    burnrates: true
    absent: true
