/*
 * Athene
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MultiBurnrateAlert struct {
	Severity string `json:"severity"`

	For int64 `json:"for"`

	Factor float64 `json:"factor"`

	Short Burnrate `json:"short"`

	Long Burnrate `json:"long"`
}
