/*
 * Athene
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Objective struct {
	Name string `json:"name"`

	Description string `json:"description"`

	Target float64 `json:"target"`

	Window int64 `json:"window"`

	Indicator Indicator `json:"indicator,omitempty"`
}
