/*
 * Athene
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IndicatorHttp struct {
	Metric string `json:"metric,omitempty"`

	Matchers []string `json:"matchers,omitempty"`

	ErrorMatchers []string `json:"errorMatchers,omitempty"`
}
