/* tslint:disable */
/* eslint-disable */
/**
 * Athene
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorBudgetPair
 */
export interface ErrorBudgetPair {
    /**
     * 
     * @type {number}
     * @memberof ErrorBudgetPair
     */
    t: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorBudgetPair
     */
    v: number;
}

export function ErrorBudgetPairFromJSON(json: any): ErrorBudgetPair {
    return ErrorBudgetPairFromJSONTyped(json, false);
}

export function ErrorBudgetPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorBudgetPair {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        't': json['t'],
        'v': json['v'],
    };
}

export function ErrorBudgetPairToJSON(value?: ErrorBudgetPair | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        't': value.t,
        'v': value.v,
    };
}


