/* tslint:disable */
/* eslint-disable */
/**
 * Athene
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IndicatorGrpc,
    IndicatorGrpcFromJSON,
    IndicatorGrpcFromJSONTyped,
    IndicatorGrpcToJSON,
    IndicatorHttp,
    IndicatorHttpFromJSON,
    IndicatorHttpFromJSONTyped,
    IndicatorHttpToJSON,
} from './';

/**
 * 
 * @export
 * @interface Indicator
 */
export interface Indicator {
    /**
     * 
     * @type {IndicatorHttp}
     * @memberof Indicator
     */
    http?: IndicatorHttp;
    /**
     * 
     * @type {IndicatorGrpc}
     * @memberof Indicator
     */
    grpc?: IndicatorGrpc;
}

export function IndicatorFromJSON(json: any): Indicator {
    return IndicatorFromJSONTyped(json, false);
}

export function IndicatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Indicator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'http': !exists(json, 'http') ? undefined : IndicatorHttpFromJSON(json['http']),
        'grpc': !exists(json, 'grpc') ? undefined : IndicatorGrpcFromJSON(json['grpc']),
    };
}

export function IndicatorToJSON(value?: Indicator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'http': IndicatorHttpToJSON(value.http),
        'grpc': IndicatorGrpcToJSON(value.grpc),
    };
}


