apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kubernetes
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/version: 0.9.0
  name: pyrra-kubernetes
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kubernetes
      app.kubernetes.io/name: pyrra
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubernetes
        app.kubernetes.io/name: pyrra
        app.kubernetes.io/version: 0.9.0
    spec:
      containers:
      - args:
        - kubernetes
        image: ghcr.io/pyrra-dev/pyrra:v0.9.0
        name: pyrra
        ports:
        - containerPort: 9099
          name: http
        - containerPort: 9443
          name: webhooks
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: pyrra-kubernetes
