apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kubernetes
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/version: 0.9.0
  name: pyrra-kubernetes
  namespace: openshift-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kubernetes
      app.kubernetes.io/name: pyrra
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubernetes
        app.kubernetes.io/name: pyrra
        app.kubernetes.io/version: 0.9.0
    spec:
      containers:
      - args:
        - kubernetes
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-private-key-file=/etc/tls/private/tls.key
        image: ghcr.io/pyrra-dev/pyrra:v0.9.0
        name: pyrra
        ports:
        - containerPort: 9099
          name: http
        - containerPort: 9443
          name: webhooks
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/tls/private
          name: tls
          readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: pyrra-kubernetes
      volumes:
      - name: tls
        secret:
          secretName: pyrra-kubernetes-tls
