apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/version: 0.9.0
  name: pyrra-api
  namespace: openshift-monitoring
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - openshift-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: pyrra
