name: Goreleaser

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GORELEASER_VERSION: v1.20.0

permissions:
  contents: write

jobs:
  build-binary:
    name: Build binary using goreleaser
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: .node-version

      - name: Build and release binaries
        uses: goreleaser/goreleaser-action@4be059cdedc660b9567bdf0a6f2824c3d2fe653f
        with:
          distribution: goreleaser
          version: ${{ env.GORELEASER_VERSION }}
          args: release --clean --timeout=60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive generated artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: pyrra-dist-binaries
          if-no-files-found: error
          path: |
            dist
            !dist/*.txt
  build-and-push-container:
    name: Container build and push
    needs: build-binary
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Set up QEMU
        uses: docker/setup-qemu-action@b99055d79363ee29ab720d5409f9c7007360c18b
        with:
          platforms: amd64.arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8016837eba79c3b51bf2025379f48b6fc50f1236

      - uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317
        with:
          name: pyrra-dist-binaries
          path: dist

      - name: Log in to the Container registry
        uses: docker/login-action@c144859092e8e353f3e118b0b329679a62351c3e
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@d24d429af23073facc066506898a0eae1f24b9ad
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@eb6512707bea5740b2608f2a43ece7bc543cb75b
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64, linux/arm/v7
